
main.out:
	g++ test.cpp glucose-3.0/simp/SimpSolver.cc glucose-3.0/core/Solver.cc -I glucose-3.0/ -o main.out

test: 
	g++ test.cpp glucose-3.0/simp/SimpSolver.cc glucose-3.0/core/Solver.cc -I glucose-3.0/ -o main.out
	./main.out

